flowchart TD
  Start([Start])
  introduction["Introduction"]
  introduction_2["Introduction 2"]
  your_previous_experience["Your Previous Experience<br/>• Have you taken a previous computer science course?<br/>• Have you taken an AP or IB course?"]
  advanced_placement_courses["Advanced Placement Courses<br/>• Which AP or IB course did you complete?<br/>• What was your score on the AP Computer Science A exam?<br/>• What was your score on the IB Computer Science exam?"]
  your_previous_experience["Your Previous Experience<br/>• Do you have previous programming experience outside of a course?"]
  topics_and_constructs["Topics and Constructs<br/>• Variables and assignment statements<br/>• Datatypes (_e.g._, `int`, `float`, `str`)<br/>• Conditionals (e.g., `if` `else`)<br/>• Loops<br/>• Lists (or arrays)<br/>• Dictionaries (or objects)<br/>• Functions and Methods"]
  code_assessment["Code Assessment<br/>• What is the output?<br/>• Which of the following best describes your experience with the preceding problem"]
  placement_section_a["Placement Section A"]
  placement_section_a["Placement Section A"]
  placement_section_a["Placement Section A"]
  placement_section_b["Placement Section B"]
  thank_you["Thank You"]
  Start --> introduction
  introduction --> introduction_2
  introduction_2 --> your_previous_experience
  dec_3{"(#Previous AP IB Course) = true"}
  your_previous_experience --> dec_3
  dec_3_yes["yes"]
  dec_3_no["no"]
  dec_3 --> dec_3_yes
  dec_3_yes --> advanced_placement_courses
  dec_3 --> dec_3_no
  dec_3_no --> your_previous_experience
  advanced_placement_courses --> your_previous_experience
  dec_5{"(state) > 2"}
  your_previous_experience --> dec_5
  dec_5_yes["yes"]
  dec_5_no["no"]
  dec_5 --> dec_5_yes
  dec_5_yes --> topics_and_constructs
  dec_5 --> dec_5_no
  dec_5_no --> code_assessment
  dec_6{"(state) > 4"}
  topics_and_constructs --> dec_6
  dec_6_yes["yes"]
  dec_6_no["no"]
  dec_6 --> dec_6_yes
  dec_6_yes --> code_assessment
  dec_6 --> dec_6_no
  dec_6_no --> placement_section_a
  dec_7{"(state) <= 1"}
  code_assessment --> dec_7
  dec_7_yes["yes"]
  dec_7_no["no"]
  dec_7 --> dec_7_yes
  dec_7_yes --> placement_section_a
  dec_7 --> dec_7_no
  dec_7_no --> placement_section_a
  dec_8{"(state) > 1 and (state) < 3"}
  placement_section_a --> dec_8
  dec_8_yes["yes"]
  dec_8_no["no"]
  dec_8 --> dec_8_yes
  dec_8_yes --> placement_section_a
  dec_8 --> dec_8_no
  dec_8_no --> placement_section_a
  dec_9{"(state) >= 3 and (state) <= 5"}
  placement_section_a --> dec_9
  dec_9_yes["yes"]
  dec_9_no["no"]
  dec_9 --> dec_9_yes
  dec_9_yes --> placement_section_a
  dec_9 --> dec_9_no
  dec_9_no --> placement_section_b
  dec_10{"(state) > 6"}
  placement_section_a --> dec_10
  dec_10_yes["yes"]
  dec_10_no["no"]
  dec_10 --> dec_10_yes
  dec_10_yes --> placement_section_b
  dec_10 --> dec_10_no
  dec_10_no --> thank_you
  placement_section_b --> thank_you
  thank_you --> Finish([Finish])
  style Start fill:#f9f,stroke:#333,stroke-width:1px
  style Finish fill:#9f9,stroke:#333,stroke-width:1px
