---
config:
  flowchart:
    curve: basis
    theme: default
---

flowchart TB
  
  subgraph C["&nbsp;"]
    your_previous_experience{"Do you have previous programming experience outside of a course?"} -- yes _(+2)_ --> condition
    your_previous_experience{"Do you have previous programming experience outside of a course?"} -- no _(+0)_ --> condition
  end
  
  score -- "`AP: 4–5 
    or IB: >= 5 
    _(+2)_`"  --> Course
  score -- "`AP: < 3 
  or IB: < 4 
  _(+0)_`" --> Course
  Course -- yes _(+1)_--> your_previous_experience
  
  
  subgraph F["&nbsp;"]
   condition -- no  _(0)_ --> End_A(["No Experience"])
  end
  condition[" <= 1 ?"] -- no --> End_B
  topics_and_constructs -- average points < 1.5  --> End_B(["Refresher"])

  condition -- yes --> topics_and_constructs
  topics_and_constructs["`Topics and Constructs 
  _(1 point for each **somewhat**, 2 points for each **entirely**)_
  `"]

  subgraph A["&nbsp;"]
      Start([Start]) --> introduction["Introduction"]
      introduction --> background["Background"]
      background -- _(0)_ --> AP{"Have you taken an AP or IB course?"}
      AP -- no _(+0)_ --> Course{"Have you taken a previous computer science course?"}
      Course -- no _(+0)_ --> your_previous_experience
  end
  
  subgraph B["&nbsp;"]
    AP -- yes _(+1)_ --> which_AP["Which AP or IB course did you complete?"]
    which_AP --> score["What was your score on the {course} exam?"]
  end

  topics_and_constructs["`Topics and Constructs 
    _(1 point for each **somewhat**, 2 points for each **entirely**)_
    `"] -- average points >= 1.5 (+2) --> code_assessment
  
  subgraph E["&nbsp;"]
    code_assessment["`Code Assessment
    _(+1 for answered correctly)_
    _(+1 for each **little difficulty**, +2 points for each **no difficulty**)_
    `"] --> condition2[" average points < 2.5 "] --> End_B
    condition2 -- average points >= 2.5 --> End_C 
    End_C(["Advanced"])
  end
  style A fill:none,stroke:none
  style B fill:none,stroke:none
  style C fill:none,stroke:none
  style E fill:none,stroke:none
  style F fill:none,stroke:none
  style Start fill:#9f9,stroke:#333,stroke-width:1px,color:#000
  style End_A fill:#f00,stroke:#333,stroke-width:1px,color:#000
  style End_B fill:#ff0,stroke:#333,stroke-width:1px,color:#000
  style End_C fill:#0f0,stroke:#333,stroke-width:1px,color:#000
  %% style End_C fill:#0f0,stroke:#333,stroke-width:1px,color:#000
